# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3842b53775e7bcc043a3bcf5b96b40be39b4b5cd09fe8b651f4528606c60676fbfb872238f4a2c19f5519c78b371dc30f099ec8e852b432ba8e8d99929d8c68e

test:
  secret_key_base: 2705b918985b34debc46b893216e2c1f92afcc9bebd0e12b0bb7121175e4932a63080308bf4358e4ad2f760fe1a2bfa59a4dbfec54a9d1b6e305814ab0b39256

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
